--LISTAR NOMBRE Y EDAD DE LOS AUTORES CUYO NOMBRE COMIENZE POR "M"

SELECT NOMBRE,EDAD
FROM AUTOR
WHERE NOMBRE LIKE 'M%'

-- LISTAR NOMBRES DE AUTORES CUYO NOMBRE TERMINE EN O. 
SELECT NOMBRE,EDAD
FROM AUTOR
WHERE NOMBRE LIKE '%O'

-- LISTAR NOMBRES DE AUTORES CUYO NOMBRE CONTENGA LA LETRA S.
SELECT NOMBRE,EDAD
FROM AUTOR
WHERE NOMBRE LIKE '%S%'

-- NUEVO TEMA... CUALIFICACION DE ATRIBUTOS

--1. SIN RENOMBRAR TABLA
-- LISTAR TITULO, NUMERO DE PAGINAS Y PRECIO DE LOS LIBROS
-- QUE TENGAN MAS DE 100 UNIDADES EN EXISTENCIA

SELECT TITULO,NPAGS,PRECIO
FROM LIBRO
WHERE existencia > 100

-- CUALIFIQUE ATRIBUTOS SIN RENOMBRAR LA TABLA

SELECT LIBRO.TITULO,LIBRO.NPAGS,LIBRO.PRECIO
FROM LIBRO
WHERE LIBRO.existencia > 100

--2. RENOMBRANDO TABLA

SELECT L.TITULO,L.NPAGS,L.PRECIO
FROM LIBRO L                      --L NUEVO NOMBRE DE LA TABLA
WHERE L.existencia > 100

-- CUALIFICAR ANTEPONER LA TABLA A CADA ATRIBUTO
-- CUALIFICAR CUANDO ES MAS DE DOS TABLAS Y RELACIONARLAS 

SELECT L.TITULO, L.NPAGS, L.PRECIO,L.CODIGO
FROM LIBRO L,GENERO G
WHERE L.EXISTENCIA > 100


-- LISTAR EL TITULO DE CADA LIBRO JUNTO CON SU PRECIO
-- Y SU PRECIO INCREMENTADO EN UN 17%


--1*1.17

SELECT L.TITULO,L.PRECIO,PRECIOAU = PRECIO+PRECIO*1.17
FROM LIBRO L

--OTHER
--COMILLAS ES POR SI TIENE ESPACIOS 
SELECT L.TITULO AS 'TITULO DEL LIBRO',
		L.PRECIO AS 'PRECIO ORIGINAL',
		L.PRECIO*1.17 AS 'PRECIO + 17%'
FROM LIBRO L

-- FUNCIONES AGREGADAS EN SQL
-- LISTAR EL PRECIO PROMEDIO DE CADA LIBRO
--5 FUNCIONES AGREGADAS.. 5 INSTRUCCIONES PARA HACER CALCULOS....
--PROMEDIO,SUMAR,CONTAR,

SELECT AVG(L.PRECIO)
FROM LIBRO L

-- OTRAS FUNCIONES AGREGADAS....

--SUM,MIN,MAX,COUNT

SELECT SUM(L.PRECIO) -- MAXIMO PRECIO
FROM LIBRO L

SELECT MIN(L.PRECIO) -- SACAR EL MINIMO
FROM LIBRO L

SELECT MAX(L.PRECIO) -- SCAR EL PRECIO MAXIMO
FROM LIBRO L

SELECT COUNT (L.PRECIO) -- CONTAR NUMERO DE CAMPOS 
FROM LIBRO L




-- LISTAR EL PROMEDIO DE LOS TITULOS DE LOS LIBROS... AVG ERROR
-- LISTAR LA SUMA DE LOS TITULOS DE LOS LIBROS ...  SUM ERROR
------------------------------------------------------------------------------
-- LISTAR EL MINIMO DE TITULOS DE UN LIBRO... MIN POR ORDEN ALFABETICO
-- LISTAR EL MAXIMO DE TITULOS DE UN LIBRO... MAX 



-- SIGUIENTE TEMA.....
-- LISTAR EL TITUO Y PRECIO DE CADA UNO DE LOS LIBROS
-- DICHA CONSULTA DEBE SALIR ORDENADA DE TAL MANERA QUE
-- EL LIBRO MAS CARO SALGA DE PRIMERO Y EL MAS BARATO DE ULTIMO


SELECT L.TITULO,L.PRECIO
FROM LIBRO L
ORDER BY L.PRECIO DESC         --  DESC (MAS ALTO AL MAS BAJO) OR  ASC (MAS BAJO AL MAS ALTO)


-- LISTAR TITULO,PRECIO, Y NUMERO DE PAGINAS DE LOS LIBROS
-- QUE TENGAN MENOS DE 200 PAGINAS. DICHA CONSULTA DEBE
-- SALIR ORDENADA ALFABETICAMENTE POR TITULO DE LIBRO

SELECT L.TITULO, L.PRECIO, L.NPAGS
FROM LIBRO L
WHERE L.NPAGS < 200
ORDER BY L.TITULO ASC       -- ASC == ALFABETICAMENTE   NO ES OBLIGATORIO EL ASC PARA ASENDENTEMENTE

--- FUNCIONES SQL ESTANDAR ....
--- PERO CADA MOTOR PUEDE CREAR NUEVAS FUNCIONES 
--- UNA FUNCION TOP ES DE EL MOTOR SQL SERVER
--- COMO LIMIT DE MYSQL O ORACLE

-- LISTAR NOMBRE Y EDAD DE LOS 2 AUTORES MAS JOVENES

SELECT TOP 2 L.NOMBRE , L.EDAD 
FROM AUTOR L
ORDER BY L.EDAD ASC   -- DESC NAS VIEJO
					   -- ASC MAS JOVEN














