-- INSERTAR A LA BASE DE DATOS

INSERT INTO LIBRO VALUES 
(100,'CIEN AÑOS DE SOLEDAD',350,1400,45000)

INSERT INTO LIBRO VALUES
(200,'MIEDO A PERDER',400,200,4000),
(300,'PINOCHO EL BRIBON',150,0,14000),
(400,'VIAJE A MARTE',220,10,41000)

INSERT INTO AUTOR VALUES
(10,'GABRIEL GARCIA MARQUEZ',80,450000,'01/25/1922'),
(20,'MARIO VARGAS LLOSA',74,960000,'09/14/1935'),
(30,'JULIO VERNE',41,470000,'12/31/1955')

-- BORRRAR EL GENERO LLAMADO NOVELA

DELETE FROM GENERO 
WHERE DESCRIPCION = 'NOVELA'OR DESCRIPCION =  'INFANTIL' OR DESCRIPCION = 'DRAMA'

-- BORRAR TODA LA TABLA

DELETE FROM GENERO

-- SUMARLE 10 A LAS EXISTENCIAS DEL LIBRO TITULADO VIAJE A MARTE


UPDATE LIBRO
SET EXISTENCIA = EXISTENCIA + 10
WHERE TITULO = 'VIAJE A MARTE'

-- INCREMENTAR A LOS LIBROS CON MAS DE 300 PAGS SU PRECIO EN UN 15% Y SUS EXISTENCIAS EN UN 8% 
-- (CON UNA SOLA INSTRUCCION DE UPDATE)

UPDATE LIBRO
SET PRECIO += PRECIO * 0.15, EXISTENCIA += 0.08
WHERE NPAGS > 300

-- VAMOS A EMPEZAR A CONSULTAR DATOS ...... ESTE TEMA SE VA
-- HASTA EL FINAL DE SEPTIEMBRE


-- LISTAR LOS DATOS DE TODOS LOS LIBROS ....

SELECT CODIGO, TITULO, NPAGS, EXISTENCIA, PRECIO
FROM LIBRO

SELECT * FROM LIBRO

--LISTAR LOS TITULOS , NUMEROS DE PAGINA Y EXISTENCIAS
-- DE LOS LIBROS CON MAS DE 325 PAGINAS Y EXISTENCIAS 
-- MENORES A 200

SELECT TITULO,NPAGS,EXISTENCIA
FROM LIBRO WHERE NPAGS >325 AND EXISTENCIA < 250

