-- INSERTAR A LA TABLA LIBRO UN NUEVO CAMPOS LLAMADO 'CODGENERO' 
--MISMO TIPO DE LA TABLA GENERO 

ALTER TABLE LIBRO
ADD CODGENERO INT

-- COMO RELACIONAR LA TABLA LIBRO Y GENERO ? 
--COMO CREARLE A LA TABLA LIBRO LA CLAVE FORENEA

ALTER TABLE LIBRO -- ADD CLAVE FORANEA
ADD FOREIGN KEY (CODGENERO)	
REFERENCES GENERO(CODIGO) -- CODIGO ES PRIMARY KEY DE LA TABLA 'GENERO'
--WARNING QUE NO HAYA LIBROS CON GENEROS QUE NO EXISTAN EN CODGENERO

--PARA LA RELACION ENTRE LIBRO Y AUTOR , COMO ES
--UNA RELACION MUCHOS A MUCHOS, SE GENERA UNA NUEVA TABLA
-- CON LAS CLAVES PRIMARIAS DE LIBRO Y AUTOR.

CREATE TABLE LIBAUTOR
(CEDAUTOR BIGINT,
CODLIBRO BIGINT,
PRIMARY KEY(CEDAUTOR,CODLIBRO))  -- CUANDO SE QUIERE ESTABLECER DOS PRIMARY KEY SE HACE AL FINAL
-- TIENE UNA PRIMARY KEY COMPUESTAS DE DOS CAMPOS
-- CUANTAS CLAVES FORANEAS TIENE LIBAUTOR 2 UNA DE UNA Y OTRA DE OTRA

------------------------------------------------------------------

-- PRIMERA CONSULTA QUE INVOLUCRA VARIAS TABLAS

-- LISTAR EL TITULO DE CADA LIBRO JUNTO CON LA
-- DESCRIPCION DE SU GENERO

SELECT L.TITULO, G.DESCRIPCION 
FROM LIBRO L INNER JOIN GENERO G
ON L.CODGENERO = G.CODIGO







