
  <footer>
  
    <table class='tabla' width='100%' cellspacing='0' color="#090" cellpadding='5'><tr class='tabla_texto_1'><td align='center' valign='top' nowrap='nowrap'><form name="busqueda_rapida" method="post" action="/search/"><b>Busqueda rapida:&nbsp;<input type="text" name="string" size="20" value="">
      </form></td></tr></table>
  <br>
     <center>Derechos reservados &copy by Company Duvan carmona</center>
  </footer>