
        <header>


		   <div id="cabezera">
               <img id="logo"  src="img/titulo.png"  align="left" alt="logo"/>
               		<center><h1>Copa Mundial de Futbol <br> Brasil-2014</center>
			      </h1>
               
			</div>
  
          <nav>
		     <ul class="bar">
			    <li><a href="Index.html">Inicio</a></li>
				<li><a href="">Noticias</a></li>
				<li><a href="">Calendario</a></li>
				<li><a href="Equipos.html">Equipos</a>
				   <ul>
				     <li><a href="">Colombia</a></li>
					 <li><a href="">Brasil</a></li>
				   </ul>
				</li>
				<li><a href="Grupos.html">Grupos</a></li>
				<li><a href="Estadios.html">Estadios</a></li>
		     </ul>
		 </nav>


		</header>
		 
       